version: '3'

services:
  app:
    image: medic84/wg-admin:latest
    container_name: app
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/html/.env
      - ./app/logs:/var/www/html/storage/logs
      - ./app/configs:/etc/wireguard
    ports:
      - "${WG_ALLOWED_PORTS:-51800-51850}:${WG_ALLOWED_PORTS:-51800-51850}/udp"
    networks:
      - wg-admin
    cap_add:
        - NET_ADMIN
        - SYS_MODULE
    sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1


  webserver:
    image: medic84/wg-admin-nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "${PANEL_HTTP_PORT:-8080}:80"
      - "${PANEL_HTTPS_PORT:-8443}:443"
    networks:
      - wg-admin

  db:
    image: postgres:14-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - wg-admin

networks:
  wg-admin:
    driver: bridge

volumes:
  dbdata:
    driver: local
