version: '3'

services:
  app:
    image: medic84/wg-admin-app:latest
    container_name: app
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/html/.env
      - ./app/logs:/var/www/html/storage/logs
      - ./app/configs:/etc/wireguard
    ports:
      - "51820:51820/udp"
    networks:
      - wg-admin
    cap_add:
        - NET_ADMIN
        - SYS_MODULE
    sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1


  webserver:
    image: medic84/wg-admin-nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - wg-admin

  db:
    image: postgres:14-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: wgadmin
      POSTGRES_USER: wgadmin
      POSTGRES_DB: wgadmin
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - wg-admin

networks:
  wg-admin:
    driver: bridge

volumes:
  dbdata:
    driver: local
